name: Build Caddy with lego_deprecated plugin

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-publish-custom-caddy:
    name: Build and publish custom Caddy image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Build Caddy image
      id: build_caddy
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: ./Containerfile
        image: ghcr.io/llyama/caddy-dns-lego
        tags: latest run-${{ github.run_number }} ${{ github.sha }}
    
    - name: Publish to GitHub registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_caddy.outputs.image }}
        tags: ${{ steps.build_caddy.outputs.tags }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
